config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :restaurants
  end

  resources :restaurants do
    resources :reviews, only: [:new, :create]

    collection do
      get :top, to: 'restaurants#top'
    end

    member do
      get :chef, to: 'restaurants#chef'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :stars, inclusion: { in: [1, 2, 3, 4, 5], message: 'must be from 1 to 5' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:chef, :show, :edit, :update, :destroy]

  def top
    @restaurants = Restaurant.where(stars: 5)
  end

  def chef
  end

  def index
    # @restaurants = Restaurant.where(published: true)
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :description, :stars)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    redirect_to @restaurant
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/index.html.erb
<h1>All restaurants</h1>

<%= link_to 'Top restaurants', top_restaurants_path, class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Stars</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.stars %></td>
        <td><%= restaurant.published? %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
  <h3>OOps!!!! You have these errors:</h3>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/chef.html.erb
<h1>Chef for <%= @restaurant.name %>:</h1>

<h2><%= @restaurant.chef %></h2>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<%= link_to 'Top restaurants', top_restaurants_path, class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<%= link_to 'Chef information', chef_restaurant_path(@restaurant) %>

<h1><%= @restaurant.name %></h1>

<p>
  <%= @restaurant.address %>
</p>

<p>
  <%= @restaurant.description %>
</p>

<p>
  <%= @restaurant.stars %>
</p>

<h2>List of reviews:</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>

<%= link_to 'Add review', new_restaurant_review_path(@restaurant), class: 'btn btn-default' %>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/top.html.erb
<h1>5 stars restaurants:</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li><%= restaurant.name %></li>
<% end %>
</ul>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name %></h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

<!-- <form action="/restaurants/7/reviews" method="post">
</form> -->